### ISSUE TITLE
Support for "extra fields"?

### ISSUE THREAD

**Issue by TheUntraceable** [Bluenix2/discord-typings#16]
Discord often send "extra fields" in events over the gateway. An example of this can be seen [here](https://discord.com/developers/docs/topics/gateway#guild-create-guild-create-extra-fields), I was unsure to if this was under the scope of this library.

**Comment by Bluenix2** [comment]
Some extra fields are supported where it makes sense. Keep in mind that adding or updating a field requires that the whole `TypedDict` is copied over.

If there are any typings for extra fields missing feel free to add it, there are very few ones which have been deliberately left out. Feel free to DM me (Bluenix#7543) to double-check before putting in the work.

As for the example you gave, it is covered in `gateway.py`:

https://github.com/Bluenix2/discord-typings/blob/7bf1452ea606547211c752667252328e789ad648/discord_typings/gateway.py#L570-L581
